name: release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    if: ${{ github.repository == 'mammothbio-os/palamedes' }}
    uses: ./.github/workflows/build.yaml

  test-release:
    name: publish to test pypi
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: test-release
      url: https://test.pypi.org/p/palamedes

    permissions:
      id-token: write

    steps:
    - name: download build
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  release:
    needs: test-release
    environment: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: download build
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: publish
      uses: pypa/gh-action-pypi-publish@release/v1

  release-github:
    needs: release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
    - name: download build
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: sign
      uses: sigstore/gh-action-sigstore-python@v3.0.0
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl

    - name: create release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: gh release create '${{ github.ref_name }}' --repo '${{ github.repository }}' --notes ""

    - name: upload release artifacts
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: gh release upload '${{ github.ref_name }}' dist/** --repo '${{ github.repository }}'
